services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=vex_db
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: